config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'interests#index'

  resources :interests

  get 'interests/:id/favorite', to: 'interests#favorite', as: 'favorite_interest'
  post 'interests/:id/comment', to: 'interests#post_comment'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :interest
end

app/models/interest.rb
class Interest < ApplicationRecord
  has_many :interest_users
  has_many :users, through: :interest_users
  has_many :comments
end

app/models/interest_user.rb
class InterestUser < ApplicationRecord
  belongs_to :interest
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :interest_users
  has_many :interests, through: :interest_users
  has_many :comments
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable, :authentication_keys => [:user_id]

  # No use email
  def email_required?
    false
  end
  
  def email_changed?
    false
  end

  def will_save_change_to_email?
    false
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:user_id, :name])
    end

  end

app/controllers/interests_controller.rb
class InterestsController < ApplicationController
  before_action :set_interest, only: [:show, :edit, :update, :destroy, :favorite, :post_comment]
  protect_from_forgery :except => [:post_comment]
  require_relative '../models/interest_user'

  # GET /interests
  # GET /interests.json
  def index
    @interests = Interest.all
  end

  # GET /interests/1
  # GET /interests/1.json
  def show
    @comment = Comment.new
  end

  # GET /interests/new
  def new
    @interest = Interest.new
  end

  # GET /interests/1/edit
  def edit
  end

  # POST /interests
  # POST /interests.json
  def create
    @interest = Interest.new(interest_params)

    respond_to do |format|
      if @interest.save
        format.html { redirect_to @interest, notice: 'Interest was successfully created.' }
        format.json { render :show, status: :created, location: @interest }
      else
        format.html { render :new }
        format.json { render json: @interest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /interests/1
  # PATCH/PUT /interests/1.json
  def update
    respond_to do |format|
      if @interest.update(interest_params)
        format.html { redirect_to @interest, notice: 'Interest was successfully updated.' }
        format.json { render :show, status: :ok, location: @interest }
      else
        format.html { render :edit }
        format.json { render json: @interest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /interests/1
  # DELETE /interests/1.json
  def destroy
    @interest.destroy
    respond_to do |format|
      format.html { redirect_to interests_url, notice: 'Interest was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def favorite
    interest_user = InterestUser.new({ interest_id: @interest.id, user_id: current_user.id })
    if interest_user.save
      @msg = "favorite success."
    else
      @msg = "already registered."
    end
  end

  def post_comment
    logger.debug(current_user.inspect())
    @comment = Comment.new({ user_id: current_user.id, interest_id: params[:id], content: params[:comment][:content] })
    @comment.save
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_interest
      @interest = Interest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def interest_params
      params.require(:interest).permit(:content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/interests_helper.rb
module InterestsHelper
end

app/views/interests/_comment.html.erb
<% comments.each do |comment| %>
  <p><%= comment.user.name %> <%= comment.content %> <%= comment.created_at %></p>
<% end %>

app/views/interests/_form.html.erb
<%= form_with(model: interest, local: true) do |form| %>
  <% if interest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(interest.errors.count, "error") %> prohibited this interest from being saved:</h2>

      <ul>
      <% interest.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content, id: :interest_content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/interests/_post.html.erb
<%= form_with(model: comment, local: true, url: "#{interest_id}/comment") do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :comment_content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/interests/edit.html.erb
<h1>Editing Interest</h1>

<%= render 'form', interest: @interest %>

<%= link_to 'Show', @interest %> |
<%= link_to 'Back', interests_path %>

app/views/interests/favorite.html.erb
<p id="notice"><%= notice %></p>

<p><%= @msg %></p>
<p>
  <strong>Content:</strong>
  <%= @interest.content %>
</p>

<%= link_to 'Back', interests_path %>

app/views/interests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Interests</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @interests.each do |interest| %>
      <tr>
        <td><%= interest.content %></td>
        <td><%= link_to 'Show', interest %></td>
        <% if user_signed_in? %>
          <td><%= link_to 'Favorite', favorite_interest_path(interest) %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Interest', new_interest_path %>

app/views/interests/new.html.erb
<h1>New Interest</h1>

<%= render 'form', interest: @interest %>

<%= link_to 'Back', interests_path %>

app/views/interests/post_comment.html.erb
<p id="notice"><%= notice %></p>

<p><%= @msg %></p>
<p>
  <strong>User:</strong>
  <%= @comment.user.name %>
</p>
<p>
  <strong>Interest:</strong>
  <%= @comment.interest.content %>
</p>
<p>
  <strong>Content:</strong>
  <%= @comment.content %>
</p>

<%= link_to 'Back', interest_path(@interest.id) %>

app/views/interests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @interest.content %>
</p>

<%= render 'comment', comments: @interest.comments %>

<% if user_signed_in? %>
  <%= render 'post', comment: @comment, interest_id: @interest.id%>
<% end %>

<%= link_to 'Edit', edit_interest_path(@interest) %> |
<%= link_to 'Back', interests_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Interest Board</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav>
        <% if user_signed_in? %>
          <strong>Hello, <%= current_user.name %></strong>
          <%= link_to 'Log out', destroy_user_session_path, method: :delete %>
        <% else %>
          <%= link_to 'Sign up', new_user_registration_path %>
          <%= link_to 'Log in', new_user_session_path %>
        <% end %>
      </nav>
    </header>
  
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    
    <%= yield %>
  </body>
</html>